namespace PdfEdit.Services;

/// <summary>A tip for the Tip of the Day dialog.</summary>
public sealed record Tip(string Title, string Text);

/// <summary>The Tip of the Day list. Shown in order, picking up where the last one left off.</summary>
public static class TipsCatalog
{
    public static readonly IReadOnlyList<Tip> All = new List<Tip>
    {
        new("Fill in any form, even a flat one",
            "Not every PDF has real form fields. Choose Add Text on the Fill & Sign tab (or press T) and click anywhere on the page to type. Your text stays editable until you flatten the file."),
        new("Single-key tools",
            "When you're not typing in a box, a single key switches tools: H Hand, V Select, T Add Text, D Date, K Check mark, X Cross, M Stamp, S Sign, I Highlight, W Draw, N Note and E Edit Fields. Press F1 for every shortcut."),
        new("Sign once, reuse everywhere",
            "Fill & Sign → New Signature… lets you draw, type or import your signature. It's saved, so next time just click Sign and drop it on the page. Make initials the same way."),
        new("Today's date in one click",
            "The Date tool (D) stamps today's date where you click. Change the format, or set the day, month and year by hand, in the Properties panel."),
        new("Ticks, crosses and dots",
            "The Marks group on Fill & Sign has a check, cross, dot, circle and line. They're ideal for paper-style forms with boxes but no real checkbox fields."),
        new("Text that fits its box",
            "Select a text box and use the popup toolbar to auto-fit the box to the text, or wrap the text inside it. Handy when a long answer won't fit a narrow space."),
        new("Let PdfEdit find the fields",
            "Edit → Detect Fields looks for the lines and boxes on a scanned or flat form and turns them into real, fillable fields, named after the label beside them."),
        new("Fill a hundred forms at once",
            "Home → Bulk Fill takes a CSV or Excel sheet and makes one filled copy of the form for every row. Columns are matched to fields by name, and you can pick how each file is named."),
        new("Let the form do the maths",
            "In a field's properties, the Format tab sets numbers, currency, percentages and dates, and the Calculate tab adds up, multiplies, averages or finds the min or max of other fields. Totals update as you type."),
        new("Batch processing",
            "Home → Batch Process runs the same steps over a whole folder: OCR, compress, watermark, flatten, rotate, page numbers, Bates numbers, passwords, PDF/A and more. Save the steps as an action to use again."),
        new("Certificate signatures",
            "Fill & Sign → Certificate… signs with a digital ID from Windows, a smart card or a .pfx file, with an optional timestamp. Fill & Sign → Signatures checks whether a signed file has changed since."),
        new("Remove what you can't see",
            "Before sending a PDF out, Home → Remove Hidden Info strips metadata, scripts, attachments and, if you choose, comments and bookmarks: leftovers you might not know are there."),
        new("Redact properly",
            "Covering text with a black box doesn't remove it. Mark areas with the Redact tool, then click Apply Redactions on the Tools tab to delete the text underneath for good."),
        new("Find and highlight",
            "Edit → Find & Highlight marks every occurrence of a word or phrase in one go. Each highlight can then be recoloured, commented on or removed."),
        new("Search a whole folder",
            "View → Search Folder looks for text in every PDF in a folder and its subfolders. Double-click a result to open that file at the right page."),
        new("Spot the difference",
            "View → Visual Compare shows two versions of a PDF side by side, with removed content in red, new content in green and changes in orange."),
        new("Have it read to you",
            "View → Read Page or Read to End reads the document aloud with a Windows voice, turning the pages as it goes. Stop Reading ends it."),
        new("Spelling as you type",
            "Text boxes, text fields and sticky notes are spell-checked with red underlines, using the dictionary for your Windows language. Turn it off in Settings → Editor."),
        new("Stamps",
            "The Stamp tool (M) has the standard business stamps, a Sign Here set and dynamic stamps that add your name and the time. Make your own, in any colour, and choose your default in Stamps…."),
        new("Watermarks behind the text",
            "Home → Watermark adds diagonal or angled text or an image, behind the content or on top, on every page or just some. The preview shows exactly how it will look."),
        new("Links that go somewhere",
            "The Link tool lets you drag a box and point it at a website, an email address or another page. With the Hand or Select tool, click a link to follow it; right-click to edit or remove it."),
        new("Page numbers and Bates numbers",
            "Home → Page Numbers adds simple numbering. For legal documents, Bates Numbers adds a prefix and running number across one or more files."),
        new("Headers and footers",
            "Home → Header / Footer puts text such as a title, date or 'Page 3 of 10' at the top or bottom of every page."),
        new("Rearrange pages by dragging",
            "Right-click a page thumbnail to rotate it, move it up or down, insert a page before or after, extract it or delete it."),
        new("Merge, split and insert",
            "Home has Merge PDFs to combine files, Split PDF to break one up, and Insert PDF to drop pages from another file in before, after or at the end."),
        new("Scan straight to PDF",
            "File → Scan works with any Windows or TWAIN scanner. Turn on OCR and the result becomes searchable, so you can find and copy its text."),
        new("Make scans searchable later",
            "Already have a scanned PDF? Run OCR from the Scan & OCR section of All tools. PdfEdit uses Windows' own OCR when the language is installed, or Tesseract otherwise (Settings → OCR)."),
        new("Measure on the page",
            "Tools → Measure has distance, perimeter and area tools. Useful for plans and drawings."),
        new("Sticky notes and comments",
            "Add a Sticky Note anywhere on the page. Every note, highlight and mark is listed in the Comments panel, where you can reply, filter and jump to it."),
        new("Undo is always there",
            "Ctrl+Z undoes almost anything, including page changes, watermarks and links. Ctrl+Y puts it back."),
        new("Let the AI design a form",
            "Design → Design Form with AI: describe what you need (a job application, a car damage report, a patient intake form) and the AI lays out fillable boxes, tick boxes, drop-downs and signature boxes for you. Or just ask for one in the AI chat."),
        new("Design your own documents",
            "The Design tab is a page layout editor. Start from a template (invoice, letter, flyer, résumé, business card) or a blank page, then export to PDF or an image."),
        new("Panels go where you want",
            "Every side panel can be dragged, docked on another side, or floated as its own window, which is handy on a second screen."),
        new("Make it bigger",
            "Ctrl+Plus and Ctrl+Minus (or View → UI Scale) make the whole window bigger or smaller, and Ctrl+0 puts it back. Ctrl+mouse wheel zooms the page. Settings → Accessibility also sets the text size of the ribbon, menus, panels, status bar and AI chat separately."),
        new("Bigger icons, bigger menus",
            "Settings → Accessibility has every size setting in one place: interface scale, text size for the whole window or each part of it (menus included), and icon size."),
        new("Have PdfEdit talk to you",
            "Settings → Accessibility can tell your screen reader about status messages, page changes and tool changes. Without a screen reader, PdfEdit can speak them itself, along with the buttons you move to with the keyboard and the tooltips."),
        new("Dark, light or high contrast",
            "View → Theme (or Settings → Appearance) switches between light, dark, high contrast, Office, Office Black, Dracula, Nord, One Dark, Monokai, Solarized and GitHub Light, or follows Windows, including its contrast themes, and can use your Windows accent colour. Every dialog follows it, title bar included."),
        new("Ask the AI about your document",
            "The AI Assistant panel reads the open PDF. Ask a question and it answers with page references; click (p. 4) to jump there."),
        new("Let the AI do the clicking",
            "Ask the assistant to fill in fields, highlight passages, add notes or stamps, or mark personal details for redaction. Each change appears as a card you Apply or Undo."),
        new("Claude, Copilot or ChatGPT",
            "The AI assistant works with Claude, GitHub Copilot's models (with a GitHub token) or ChatGPT. Pick one with the tabs at the top of the model picker in the AI panel, and connect it with the key icon."),
        new("Free, private AI",
            "You don't need a paid AI account. Point PdfEdit at a local model (Ollama, LM Studio and others) in Settings → AI Assistant and nothing leaves your PC."),
        new("Profiles for repeat forms",
            "Save your details (name, address, date of birth and so on) as a profile on the AI Assistant tab. Smart Fill then uses them to complete new forms."),
        new("Export and import form data",
            "Edit → Export Data saves the filled values to a file; Import Data fills another copy of the form from it. Good for forms you send every year."),
        new("Flatten before sending",
            "Flatten & Save turns fields and annotations into ordinary page content, so they look the same in every viewer and can't be changed by accident."),
        new("Lock it with a password",
            "Home → Password Protect sets a password to open the file, and can stop printing, copying or editing."),
        new("Archive-ready PDFs",
            "Edit → Archive (PDF/A) saves a copy in the long-term archive format that libraries, courts and records offices ask for."),
        new("Is it accessible?",
            "View → Accessibility Check tests the things screen readers depend on (title, language, tags, alternative text, field and link descriptions, tab order) and fixes the common ones in one click."),
        new("Open Word files directly",
            "Ctrl+O opens Word documents as well as PDFs: they're turned into a PDF next to the original. Word (.docx) works even without Microsoft Office installed."),
        new("Word forms stay fillable",
            "Importing a Word form turns its content controls, form fields, ☐ boxes and ______ blanks into real PDF fields in the same places, ready to fill in."),
        new("Bring in a Google Doc",
            "Home → From Google Docs takes a link to a Google Doc, Sheet or Slides file and opens it as a PDF. Import from Cloud brings in Google Docs from Google Drive too."),
        new("Word, Excel and PowerPoint to PDF",
            "Home → From Office turns Word, Excel and PowerPoint files into PDFs, or just drag them onto the window. Word documents keep their headings as bookmarks. It uses Microsoft Office, or the free LibreOffice."),
        new("Tables into Excel",
            "Edit → Export to Excel rebuilds the tables on each page as rows and columns, with amounts and percentages stored as numbers, ready to total up."),
        new("Several PDFs at once",
            "Every PDF you open gets a tab above the page. Ctrl+Tab moves between them, Ctrl+W closes one, and a middle-click closes a tab. Unsaved work in each tab is kept while you switch."),
        new("Google Drive and OneDrive",
            "Home → Import from Cloud brings PDFs, Word files and Google Docs in from Google Drive or OneDrive, and Save to Cloud saves your PDF there. Set it up once in Settings → Cloud with your own app details."),
        new("Ask about any passage",
            "Press Shift+S (or AI Assistant → Select Text) and drag over some text. A small bar offers Copy, Highlight, Explain, Summarise, Rewrite, Translate and Ask. Drag over a chart or a scan and choose Ask about this area to send the AI a picture of it."),
        new("An outline of the whole document",
            "AI Assistant → Outline writes a summary in its own panel: an overview, each section's key points, and page links you can click."),
        new("Let the AI write it up",
            "AI Assistant → Write turns the open PDF into an email, study notes, flashcards, a quiz, an FAQ, a list of actions and deadlines, or a plain-English version."),
        new("Just ask it to do things",
            "The assistant can run PdfEdit for you: try “compress this”, “export it to Word”, “zoom to fit the width” or “read this page to me”. Each one shows as a card you Apply."),
        new("Ask out loud",
            "Click the microphone in the AI panel and speak your question. Windows needs online speech recognition switched on (Settings → Privacy & security → Speech)."),
        new("Present a PDF",
            "View → Slide Show shows the document full screen, a page at a time. Arrow keys or a click move on, B blanks the screen, and Esc ends the show."),
        new("Easier on the eyes",
            "View → Night Mode darkens the pages themselves for reading at night, and Two Pages shows the next page beside the current one."),
        new("PowerPoint and pictures",
            "Edit → Export to PowerPoint makes one slide per page; Extract Images saves every picture in the PDF to a folder."),
        new("Translate the whole PDF",
            "AI Assistant → Translate PDF makes a translated copy that keeps the layout: every paragraph is rewritten in place in the new language."),
        new("One question, many PDFs",
            "AI Assistant → Ask Across PDFs answers from several files or a whole folder at once, citing the file and page. Click a source to open it there."),
        new("See it as a mind map",
            "AI Assistant → Mind Map turns the document into a map of topics and key points. Click a topic to jump to its page, or save the map as a picture."),
        new("Tidy up scans",
            "Home → Clean Up Scans finds blank pages, pages scanned at an angle and two pages scanned side by side, and fixes them in one go."),
        new("Your own shortcuts",
            "Settings → Keyboard lists every command. Pick one, press the keys you want and click Assign. Give your favourite tools single keys, or put Ctrl+ shortcuts on the commands you use most."),
        new("Find the right tool fast",
            "The All tools panel on the left lists everything PdfEdit can do, grouped by what you want to do. Start typing in its search box to filter."),
        new("Take the tour again",
            "Missed something? File → Take the Tour walks you through the main parts of the window, and this dialog lives under File → Tip of the Day."),
    };
}
